# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'price.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests as re

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1122, 857)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(170, 250, 131, 51))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(190, 330, 93, 28))
        self.pushButton.setObjectName("pushbutton")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(460, 170, 651, 581))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 450, 461, 301))
        self.textBrowser_2.setObjectName("textBrowser_2")

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(self.get_data)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    
    def get_data(self):
        def price():
                url = 'https://api.accessban.com/v1/data/sana/json'
                response = re.get(url)
                js = response.json()
                my_list = []
                s = str(js)
                number_list = ['1','2','3','4','5','6','7','8','9','0']
                number_list_2 = []
                string = ''
                number_string = ''
                text = self.lineEdit.text()
                split = text.split()
                requests_list = []
                for item in split:
                    requests_list.append(item)
                for r in requests_list:
                        request = r
                        for char in s:
                                string+=char
                                if(char==' ' or char=="'" or char==','):
                                    string = ''
                                    if(number_string!=''):
                                        number_list_2.append(number_string)
                                        number_string = ''
                                        my_list.remove('shod')
                                if(string=='sana_buy_%s' %(request)):
                                    my_list.append('shod')
                                if(char in number_list and 'shod' in my_list):
                                    number_string+=char
                count = 1
                index = 0
                for item in number_list_2:
                    if(count==1):
                        self.textBrowser.setText('the price of %s is %s' %(requests_list[index],item))
                        count = 0
                    else:
                        self.textBrowser.append('the price of %s is %s' %(requests_list[index],item))
                    index+=1
        price()
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "اجرا"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
    app.processEvents()